name: test_and_build_linux_amd64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/setup-nasm@v1
        with:
          platform: linux

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        working-directory: .
        run: cargo run -- test --all --use=asm-elf64 --print test
